# Vendoring generated by rust2rpm, merged with X11-specific packaging

%global crate xcolor
%global debug_package %{nil}

Name: xcolor
Version: 0.5.1
Release: 1%{?dist}
Summary: Lightweight color picker for X11

License: MIT
URL: https://github.com/Soft/xcolor
Source0: %{crates_source}
Source1: xcolor-0.5.1-vendor.tar.xz

BuildRequires: cargo-rpm-macros
BuildRequires: pkg-config
BuildRequires: glibc-devel
BuildRequires: libX11-devel
BuildRequires: libXcursor-devel
BuildRequires: libxcb-devel

%description
xcolor is a lightweight, scriptable color picker for X11. It provides a
simple CLI tool to pick colors from screen and output them in various
formats. It uses the Xlib and XCB libraries for screen capture and
cursor information.

%prep
%autosetup -n %{crate}-%{version} -p1 -a1
%cargo_prep -v vendor

%build
%cargo_build
%{cargo_license_summary}
%{cargo_license} >LICENSE.dependencies
%{cargo_vendor_manifest}

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%files
%license LICENSE
%license LICENSE.dependencies
%{_bindir}/xcolor

%changelog
* Mon Aug 17 2026 0.5.1-1
- Initial package
